In [32]:
from google.cloud import bigquery
import requests
import pandas as pd
import db_dtypes

client = bigquery.Client(project="healthcare-test-486920")

In [ ]:

sql = """
SELECT
    distinct code from
    (
        SELECT CAST(diagnosis1 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis1 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis2 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis2 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis3 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis3 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis4 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis4 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis5 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis5 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis6 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis6 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis7 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis7 IS NOT NULL
        UNION ALL
        SELECT CAST(diagnosis8 AS STRING) AS code FROM `healthcare-test-486920.Raw_csvs_test.claims_slim` WHERE diagnosis8 IS NOT NULL
    )t
"""

job = client.query(sql)
rows = list(job.result())


data = [dict(r) for r in rows]
conditions = pd.DataFrame(data)

                code
0            3718001
1            5602001
2            6072007
3            6525002
4            7200002
..               ...
247        249497008
248  132281000119108
249        706870000
250        770349000
251         43724002

[252 rows x 1 columns]

In [ ]:
sql = """
SELECT
    distinct code from healthcare-test-486920.Raw_csvs_test.procedures_slim
"""

job = client.query(sql)
rows = list(job.result())


data = [dict(r) for r in rows]
procedures = pd.DataFrame(data)

In [40]:
procedures

                code
0          710841007
1          710824005
2    428211000124100
3          763302001
4          762998009
..               ...
297         35025007
298        313660005
299          9564003
300        315124004
301         78429003

[302 rows x 1 columns]

In [41]:
import json 

BASE_URL = "https://snowstorm.snomedtools.org/fhir" 
SNOMED_URL = "http://snomed.info/sct"

def snomed_lookup(code: str):
    """Call FHIR CodeSystem/$lookup for a SNOMED CT code and return JSON."""
    params = {
        "system": SNOMED_URL,
        "code": code
    }
    url = f"{BASE_URL}/CodeSystem/$lookup"
    resp = requests.get(url, params=params)
    resp.raise_for_status()
    return resp.json()

result = snomed_lookup("22298006")
print(json.dumps(result, indent=2)[:2000])

HTTPError: 429 Client Error: Too Many Requests for url: https://snowstorm.snomedtools.org/fhir/CodeSystem/$lookup?system=http%3A%2F%2Fsnomed.info%2Fsct&code=22298006