In [52]:
import time
import requests
import json
from pathlib import Path
import pandas as pd
from data import load_data

# ----- CONFIGURE THESE -----
data_path = r"D:\Python Projects\Hospital readmission risk\data\raw\dictionaries\unique_procedures.csv"
write_path = r"D:\Python Projects\Hospital readmission risk\data\processed\dictionaries\procedures_dictionary.csv"
procedure_sql = """
    select * 
    from `raw_data_for_dictionaries.unique_procedures`
"""
diagnoses_sql = """
    select *
    from `raw_data_for_dictionaries.unique_diagnoses`
"""
BASE = "https://termbrowser.nhs.uk/sct-browser-api/snomed"
EDITION = "uk-edition"
RELEASE = "v20251119"  # keep in sync with what you see in the browser
MAX_RETRIES = 3
BACKOFF_SECONDS = 2.0
STATE_PATH = Path("D:\Python Projects\Hospital readmission risk\data\intermediate\procedures_snomed_state.json")
CACHE: dict[str, dict] = {}
RESULTS: dict[str, dict[str, bool]] = {} 
procedure_targets = {
    "is_procedure": {
        "243796009", #situation
        "14734007", #admin_procedure
        "409073007", #education_procedure
        "108217004", #interview, history, physical examination
        "119270007", #management procedure
        "185316007", #indirect encounter
        "122869004", #measurement procedure
        "363787002", #observation
        "404684003", #clinical finding
        "72353004", #psychosocial
        "260787004", #physical_object
        "11429006" #consultation
                    },
    "is_therapy" : {"243120004"}
}    
diagnosis_targets = {
    "is_dementia" : "52448006",
    "is_cancer" : "363346000",
    "is_hiv": "86406008",
    "is_hf": "105981003",
    "is_ckd": "709044004",
    "is_diabetes": "44054006",
    "is_lf" : "235856003",
    "is_chronic": "27624003"
}
    
    
    # concept_id -> True/False results
session = requests.Session()
# ----------------------------

In [3]:
def load_state():

    global CACHE, RESULTS

    if not STATE_PATH.exists():
        return

    with STATE_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)

    CACHE = data.get("cache", {})

    raw_results = data.get("results", {})  # dict[str, dict]
    RESULTS = {
        code: {flag: bool(val) for flag, val in flags.items()}
        for code, flags in raw_results.items()
            }

In [4]:
def save_state():

    data = {
        "cache": CACHE,
        "results": RESULTS,
    }
    
    with STATE_PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f)

In [5]:

def get_concept(concept_id: str) -> dict:
    """Fetch a SNOMED concept JSON once, with simple 429 handling and caching."""

    if concept_id in CACHE:

        return CACHE[concept_id]

    url = f"{BASE}/{EDITION}/{RELEASE}/concepts/{concept_id}"

    for attempt in range(1, MAX_RETRIES + 1):

        resp = session.get(url)

        if resp.status_code == 429:
            # too many requests - small backoff then retry
            time.sleep(BACKOFF_SECONDS * attempt)
            continue

        if resp.status_code in (404, 410, 500, 502, 503, 504):

            CACHE[concept_id] = {}

            for flag in procedure_targets:
                RESULTS[flag][concept_id] = False
                
            #save_state()
            return {}

        resp.raise_for_status()

        data = resp.json()

        CACHE[concept_id] = data

        #save_state()
        
        return data

    # if we get here, all retries hit 429 or other non-OK without raise
    resp.raise_for_status()

In [6]:
def get_parent_ids(concept: dict) -> list[str]:

    """Extract parent conceptIds from the concept JSON (adjust to actual structure)."""

    parents = []

    for rel in concept.get("relationships", []):
        # 'is a' relationship has conceptId 116680003 in SNOMED CT
        if rel.get("type", {}).get("conceptId") == "116680003" and rel.get("active"):

            target = rel.get("target") or {}

            cid = target.get("conceptId")

            if cid:
                
                parents.append(cid)
            
    return parents

In [44]:
def has_ancestor_in(concept_id: str, target_ids: set[str], flag: str, max_depth: int = 10) -> bool:
    # if we’ve already fully explored this concept’s ancestors in a previous run,
    # just return the previous answer if you also store it, or skip re-walk.

    if flag not in RESULTS: 
        RESULTS[flag] = {}

    if concept_id in RESULTS[flag]:
        return RESULTS[flag][concept_id]

    visited = set()
    frontier = {concept_id}
    result = False

    for depth in range(max_depth):

        next_frontier = set()

        for cid in frontier:

            if cid in visited:
                continue

            if cid in RESULTS[flag] and RESULTS[flag][cid]:

                RESULTS[flag][concept_id] = True
                #save_state()
                return True

            visited.add(cid)

            c = get_concept(cid)

            if not isinstance(c, dict):
                continue

            parents = get_parent_ids(c)

            if target_ids.intersection(parents):

                result = True
                
                RESULTS[flag][cid] = True
                RESULTS[flag][concept_id] = True
                #save_state()

                return True
            
            next_frontier.update(p for p in parents if p not in visited)

            # tiny pause to be gentle, even though this is just one chain
            time.sleep(0.1)

        if not next_frontier:
            break
        
        frontier = next_frontier

    RESULTS[flag][concept_id] = False
    #save_state()

    return result

In [28]:
def build_dictionary(data):

    for id in data['code']:

        for flag in procedure_targets:

            b = has_ancestor_in(id, procedure_targets[flag], flag)

In [27]:
def build_flags(data: pd.DataFrame):

    data.set_index('code', inplace = True)

    for flag in RESULTS:
    
        col = pd.Series(RESULTS[flag])
        col = col.to_frame(name = flag)
        data[flag] = col

In [10]:
def get_description(concept_id):

    if CACHE[concept_id]:

        return CACHE[concept_id].get("descriptions", []).get("term")

    return None

In [11]:
def fill_descriptions(data):

    for id in data.index:

        if data.loc[id, 'description'] is None:
            
            data.loc[id, 'description'] = get_description(id)

In [12]:
def pack_dictionary(data):

    data.to_csv(write_path)

In [50]:
if __name__ == "__main__":

    load_state()
    
    data = load_data(data_path, procedure_sql)           # load previous results

    try:
        
        build_dictionary(data)

    finally:
        save_state()

        
    build_flags(data)
    fill_descriptions(data)
    pack_dictionary(data)

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [55]:
build_flags(data)
fill_descriptions(data)

KeyError: "None of ['code'] are in the columns"

In [56]:
data

                                                 description
code
23426006     Measurement of respiratory function (procedure)
3802001    Dental application of desensitizing medicament...
223470000    Discussion about signs and symptoms (procedure)
58000006                       Patient discharge (procedure)
287664005  Ligation of bilateral fallopian tubes (procedure)
...                                                      ...
434363004  Human epidermal growth factor receptor 2 gene ...
433114000  Human epidermal growth factor receptor 2 gene ...
105376000       Transesophageal echocardiography (procedure)
408919008                 Psychosocial care (regime/therapy)
171126009                 Tuberculosis screening (procedure)

[402 rows x 1 columns]

In [51]:
save_state()

In [57]:
RESULTS['is_therapy']

KeyError: 'is_therapy'

In [13]:
RESULTS

{'is_procedure': {'23426006': True,
  '3802001': False,
  '223470000': False,
  '58000006': True,
  '287664005': False,
  '363259005': True,
  '306316000': True,
  '64777005': True,
  '866146005': True,
  '399217008': False,
  '241055006': False,
  '112798008': False,
  '84100007': True,
  '67879005': True,
  '714812005': False,
  '223464006': True,
  '304531008': True,
  '418824004': False,
  '232717009': False,
  '301884003': False,
  '430925007': True,
  '104326007': True,
  '12719002': False,
  '229064008': False,
  '43075005': False,
  '129125009': True,
  '183976008': True,
  '770695002': True,
  '16335031000119103': False,
  '396487001': False,
  '410314003': True,
  '762993000': False,
  '233553003': False,
  '703423002': False,
  '315306007': True,
  '85765000': True,
  '390791001': True,
  '38102005': False,
  '88848003': False,
  '79733001': False,
  '103750000': False,
  '185087000': True,
  '709138001': True,
  '271280005': False,
  '57617002': False,
  '133899007': False,
  '305056002': True,
  '305351004': True,
  '223487003': False,
  '171128005': False,
  '118629009': True,
  '229069003': True,
  '183519002': True,
  '713106006': False,
  '441550005': False,
  '15220000': False,
  '116861002': False,
  '63332003': True,
  '37542007': False,
  '432231006': False,
  '311791003': True,
  '118218001': True,
  '26604007': True,
  '34896006': False,
  '252480006': False,
  '306206005': True,
  '40617009': False,
  '9564003': True,
  '34043003': True,
  '1260009003': False,
  '392134007': True,
  '736169004': True,
  '394894008': False,
  '223474009': True,
  '709010006': True,
  '225337009': False,
  '90407005': False,
  '64572001': True,
  '65710008': True,
  '42825003': False,
  '47227006': False,
  '182832007': True,
  '430193006': True,
  '252832004': True,
  '243063003': True,
  '710839006': False,
  '117010004': False,
  '35025007': True,
  '9905009': False,
  '84728005': True,
  '1260010008': False,
  '229095001': False,
  '304532001': True,
  '91602002': False,
  '715252007': False,
  '306706006': True,
  '14736009': False,
  '71651007': False,
  '1287742003': False,
  '165355002': True,
  '104435004': True,
  '234745004': False,
  '314098000': False,
  '246464006': True,
  '386216000': True,
  '371361000119107': True,
  '171122006': False,
  '167252002': False,
  '386053000': False,
  '443529005': False,
  '169673001': True,
  '308291000': True,
  '449214001': True,
  '18286008': False,
  '709506004': False,
  '709640007': False,
  '274474001': False,
  '274788003': True,
  '71493000': False,
  '49062001': True,
  '261352009': True,
  '165197003': False,
  '127325009': True,
  '365853002': True,
  '122856003': True,
  '22523008': False,
  '413107006': False,
  '16076005': True,
  '33633005': True,
  '243150007': False,
  '74857009': True,
  '63697000': False,
  '399014008': False,
  '11466000': False,
  '165829005': True,
  '104091002': True,
  '426701000119108': False,
  '313660005': True,
  '431182000': False,
  '65677008': False,
  '169553002': False,
  '76601001': False,
  '52734007': False,
  '122460008': True,
  '303653007': False,
  '306237005': True,
  '40701008': False,
  '223495004': False,
  '446573003': False,
  '306185001': True,
  '8290005': False,
  '762998009': False,
  '69212005': True,
  '385892002': False,
  '609588000': False,
  '709979004': False,
  '16830007': True,
  '25656009': True,
  '85548006': False,
  '76164006': False,
  '24832002': False,
  '24623002': False,
  '447759004': False,
  '252895004': False,
  '302761001': False,
  '82808001': False,
  '90226004': False,
  '90470006': False,
  '122869004': False,
  '183450002': True,
  '117015009': False,
  '54550000': False,
  '268400002': False,
  '37729005': True,
  '417656005': True,
  '281790008': False,
  '415300000': True,
  '236974004': False,
  '107727007': True,
  '312853008': True,
  '225297008': True,
  '1259293006': False,
  '225362009': False,
  '180178009': False,
  '428830000': False,
  '60218003': False,
  '10383002': False,
  '248982007': True,
  '367494004': True,
  '367336001': False,
  '113076002': True,
  '302351005': False,
  '710824005': False,
  '713026007': False,
  '81733005': False,
  '301882004': False,
  '171231001': False,
  '58776007': False,
  '413180006': False,
  '305428000': True,
  '428211000124100': False,
  '1256042007': False,
  '225415001': False,
  '133900002': False,
  '30088009': False,
  '404909007': False,
  '23745001': True,
  '371908008': False,
  '76746007': False,
  '80146002': False,
  '167995008': True,
  '45595009': True,
  '410299006': True,
  '313077009': False,
  '228558003': True,
  '386516004': True,
  '61746007': True,
  '275833003': True,
  '269828009': True,
  '237001001': False,
  '177765008': False,
  '234336002': False,
  '232965003': False,
  '445528004': True,
  '288086009': False,
  23426006: True,
  3802001: False,
  223470000: False,
  58000006: True,
  287664005: False,
  306316000: True,
  866146005: True,
  399217008: False,
  241055006: False,
  112798008: False,
  67879005: True,
  714812005: False,
  304531008: True,
  418824004: False,
  232717009: False,
  301884003: False,
  104326007: True,
  12719002: False,
  229064008: False,
  43075005: False,
  183976008: True,
  770695002: True,
  16335031000119103: False,
  396487001: False,
  410314003: True,
  762993000: False,
  233553003: False,
  703423002: False,
  85765000: True,
  390791001: True,
  38102005: False,
  88848003: False,
  79733001: False,
  103750000: False,
  709138001: True,
  271280005: False,
  57617002: False,
  133899007: False,
  305351004: True,
  223487003: False,
  171128005: False,
  229069003: True,
  183519002: True,
  713106006: False,
  441550005: False,
  15220000: False,
  116861002: False,
  63332003: True,
  37542007: False,
  432231006: False,
  311791003: True,
  26604007: True,
  34896006: False,
  252480006: False,
  306206005: True,
  40617009: False,
  9564003: True,
  34043003: True,
  1260009003: False,
  736169004: True,
  394894008: False,
  709010006: True,
  225337009: False,
  90407005: False,
  65710008: True,
  42825003: False,
  47227006: False,
  430193006: True,
  252832004: True,
  243063003: True,
  710839006: False,
  117010004: False,
  35025007: True,
  9905009: False,
  84728005: True,
  1260010008: False,
  229095001: False,
  304532001: True,
  91602002: False,
  715252007: False,
  306706006: True,
  14736009: False,
  71651007: False,
  1287742003: False,
  165355002: True,
  104435004: True,
  234745004: False,
  314098000: False,
  386216000: True,
  371361000119107: True,
  171122006: False,
  167252002: False,
  386053000: False,
  443529005: False,
  169673001: True,
  449214001: True,
  18286008: False,
  709506004: False,
  709640007: False,
  274474001: False,
  274788003: True,
  71493000: False,
  261352009: True,
  165197003: False,
  365853002: True,
  122856003: True,
  22523008: False,
  413107006: False,
  33633005: True,
  243150007: False,
  74857009: True,
  63697000: False,
  399014008: False,
  11466000: False,
  165829005: True,
  104091002: True,
  426701000119108: False,
  313660005: True,
  431182000: False,
  65677008: False,
  169553002: False,
  76601001: False,
  52734007: False,
  122460008: True,
  303653007: False,
  306237005: True,
  40701008: False,
  223495004: False,
  446573003: False,
  306185001: True,
  8290005: False,
  762998009: False,
  69212005: True,
  385892002: False,
  609588000: False,
  709979004: False,
  16830007: True,
  25656009: True,
  85548006: False,
  76164006: False,
  24832002: False,
  24623002: False,
  447759004: False,
  252895004: False,
  302761001: False,
  82808001: False,
  90226004: False,
  90470006: False,
  122869004: False,
  183450002: True,
  117015009: False,
  54550000: False,
  268400002: False,
  37729005: True,
  417656005: True,
  281790008: False,
  415300000: True,
  236974004: False,
  312853008: True,
  225297008: True,
  1259293006: False,
  225362009: False,
  180178009: False,
  428830000: False,
  60218003: False,
  10383002: False,
  367494004: True,
  367336001: False,
  113076002: True,
  302351005: False,
  710824005: False,
  713026007: False,
  81733005: False,
  84100007: True,
  301882004: False,
  171231001: False,
  58776007: False,
  413180006: False,
  305428000: True,
  428211000124100: False,
  1256042007: False,
  225415001: False,
  133900002: False,
  30088009: False,
  404909007: False,
  23745001: True,
  371908008: False,
  76746007: False,
  80146002: False,
  167995008: True,
  45595009: True,
  410299006: True,
  313077009: False,
  386516004: True,
  61746007: True,
  275833003: True,
  269828009: True,
  237001001: False,
  177765008: False,
  234336002: False,
  232965003: False,
  445528004: True,
  288086009: False},
 'is_therapy': {'23426006': False,
  '3802001': False,
  '223470000': False,
  '58000006': False,
  '287664005': False,
  '306316000': False,
  '866146005': False,
  '399217008': False,
  '241055006': False,
  '112798008': False,
  '67879005': False,
  '714812005': False,
  '304531008': False,
  '418824004': False,
  '232717009': False,
  '301884003': False,
  '104326007': False,
  '12719002': False,
  '225365006': True,
  '229064008': True,
  '43075005': False,
  '183976008': False,
  '770695002': False,
  '16335031000119103': False,
  '396487001': False,
  '410314003': False,
  '762993000': False,
  '233553003': False,
  '703423002': False,
  '85765000': False,
  '390791001': False,
  '38102005': False,
  '88848003': False,
  '79733001': False,
  '103750000': False,
  '709138001': False,
  '271280005': False,
  '57617002': False,
  '133899007': True,
  '305351004': False,
  '223487003': False,
  '171128005': False,
  '229069003': False,
  '183519002': False,
  '713106006': False,
  '441550005': False,
  '15220000': False,
  '116861002': False,
  '63332003': False,
  '37542007': False,
  '432231006': False,
  '311791003': False,
  '26604007': False,
  '34896006': False,
  '252480006': False,
  '306206005': False,
  '133877004': True,
  '40617009': True,
  '9564003': False,
  '34043003': False,
  '1260009003': False,
  '736169004': False,
  '394894008': False,
  '709010006': False,
  '225337009': False,
  '90407005': False,
  '65710008': False,
  '42825003': False,
  '47227006': False,
  '430193006': False,
  '252832004': False,
  '243063003': False,
  '710839006': False,
  '117010004': False,
  '35025007': False,
  '9905009': False,
  '84728005': False,
  '1260010008': False,
  '229095001': True,
  '304532001': False,
  '91602002': False,
  '715252007': False,
  '306706006': False,
  '14736009': False,
  '71651007': False,
  '1287742003': False,
  '165355002': False,
  '104435004': False,
  '234745004': False,
  '314098000': False,
  '386216000': False,
  '371361000119107': False,
  '171122006': False,
  '167252002': False,
  '386053000': False,
  '443529005': False,
  '169673001': False,
  '449214001': False,
  '18286008': False,
  '709506004': False,
  '709640007': False,
  '274474001': False,
  '274788003': False,
  '71493000': False,
  '261352009': False,
  '165197003': False,
  '365853002': False,
  '122856003': False,
  '22523008': False,
  '413107006': False,
  '33633005': False,
  '1149092001': True,
  '243150007': True,
  '74857009': False,
  '63697000': False,
  '399014008': False,
  '11466000': False,
  '165829005': False,
  '104091002': False,
  '426701000119108': False,
  '313660005': False,
  '431182000': False,
  '65677008': False,
  '169553002': False,
  '76601001': False,
  '52734007': False,
  '122460008': False,
  '303653007': False,
  '306237005': False,
  '40701008': False,
  '225318000': True,
  '223495004': True,
  '446573003': False,
  '306185001': False,
  '8290005': False,
  '762998009': False,
  '69212005': False,
  '385892002': False,
  '609588000': False,
  '709979004': False,
  '16830007': False,
  '25656009': False,
  '85548006': False,
  '76164006': False,
  '24832002': False,
  '24623002': False,
  '447759004': False,
  '252895004': False,
  '302761001': False,
  '239516002': True,
  '82808001': True,
  '90226004': False,
  '90470006': False,
  '122869004': False,
  '183450002': False,
  '117015009': False,
  '54550000': False,
  '268400002': False,
  '37729005': False,
  '417656005': False,
  '281790008': False,
  '415300000': False,
  '236974004': False,
  '312853008': False,
  '225297008': False,
  '1259293006': False,
  '225362009': True,
  '180178009': False,
  '428830000': False,
  '60218003': False,
  '10383002': False,
  '367494004': False,
  '367336001': False,
  '113076002': False,
  '302351005': False,
  '710824005': False,
  '713026007': False,
  '81733005': False,
  '84100007': False,
  '301882004': False,
  '171231001': False,
  '58776007': False,
  '413180006': False,
  '305428000': False,
  '428211000124100': False,
  '1256042007': False,
  '225415001': True,
  '133900002': True,
  '30088009': False,
  '404909007': False,
  '23745001': False,
  '371908008': False,
  '76746007': False,
  '80146002': False,
  '167995008': False,
  '45595009': False,
  '410299006': False,
  '313077009': False,
  '386516004': False,
  '61746007': False,
  '275833003': False,
  '269828009': False,
  '237001001': False,
  '177765008': False,
  '234336002': False,
  '232965003': False,
  '445528004': False,
  '288086009': False,
  23426006: False,
  3802001: False,
  223470000: False,
  58000006: False,
  287664005: False,
  306316000: False,
  866146005: False,
  399217008: False,
  241055006: False,
  112798008: False,
  67879005: False,
  714812005: False,
  304531008: False,
  418824004: False,
  232717009: False,
  301884003: False,
  104326007: False,
  12719002: False,
  229064008: True,
  43075005: False,
  183976008: False,
  770695002: False,
  16335031000119103: False,
  396487001: False,
  410314003: False,
  762993000: False,
  233553003: False,
  703423002: False,
  85765000: False,
  390791001: False,
  38102005: False,
  88848003: False,
  79733001: False,
  103750000: False,
  709138001: False,
  271280005: False,
  57617002: False,
  133899007: True,
  305351004: False,
  223487003: False,
  171128005: False,
  229069003: False,
  183519002: False,
  713106006: False,
  441550005: False,
  15220000: False,
  116861002: False,
  63332003: False,
  37542007: False,
  432231006: False,
  311791003: False,
  26604007: False,
  34896006: False,
  252480006: False,
  306206005: False,
  40617009: True,
  9564003: False,
  34043003: False,
  1260009003: False,
  736169004: False,
  394894008: False,
  709010006: False,
  225337009: False,
  90407005: False,
  65710008: False,
  42825003: False,
  47227006: False,
  430193006: False,
  252832004: False,
  243063003: False,
  710839006: False,
  117010004: False,
  35025007: False,
  9905009: False,
  84728005: False,
  1260010008: False,
  229095001: True,
  304532001: False,
  91602002: False,
  715252007: False,
  306706006: False,
  14736009: False,
  71651007: False,
  1287742003: False,
  165355002: False,
  104435004: False,
  234745004: False,
  314098000: False,
  386216000: False,
  371361000119107: False,
  171122006: False,
  167252002: False,
  386053000: False,
  443529005: False,
  169673001: False,
  449214001: False,
  18286008: False,
  709506004: False,
  709640007: False,
  274474001: False,
  274788003: False,
  71493000: False,
  261352009: False,
  165197003: False,
  365853002: False,
  122856003: False,
  22523008: False,
  413107006: False,
  33633005: False,
  243150007: True,
  74857009: False,
  63697000: False,
  399014008: False,
  11466000: False,
  165829005: False,
  104091002: False,
  426701000119108: False,
  313660005: False,
  431182000: False,
  65677008: False,
  169553002: False,
  76601001: False,
  52734007: False,
  122460008: False,
  303653007: False,
  306237005: False,
  40701008: False,
  223495004: True,
  446573003: False,
  306185001: False,
  8290005: False,
  762998009: False,
  69212005: False,
  385892002: False,
  609588000: False,
  709979004: False,
  16830007: False,
  25656009: False,
  85548006: False,
  76164006: False,
  24832002: False,
  24623002: False,
  447759004: False,
  252895004: False,
  302761001: False,
  82808001: True,
  90226004: False,
  90470006: False,
  122869004: False,
  183450002: False,
  117015009: False,
  54550000: False,
  268400002: False,
  37729005: False,
  417656005: False,
  281790008: False,
  415300000: False,
  236974004: False,
  312853008: False,
  225297008: False,
  1259293006: False,
  225362009: True,
  180178009: False,
  428830000: False,
  60218003: False,
  10383002: False,
  367494004: False,
  367336001: False,
  113076002: False,
  302351005: False,
  710824005: False,
  713026007: False,
  81733005: False,
  84100007: False,
  301882004: False,
  171231001: False,
  58776007: False,
  413180006: False,
  305428000: False,
  428211000124100: False,
  1256042007: False,
  225415001: True,
  133900002: True,
  30088009: False,
  404909007: False,
  23745001: False,
  371908008: False,
  76746007: False,
  80146002: False,
  167995008: False,
  45595009: False,
  410299006: False,
  313077009: False,
  386516004: False,
  61746007: False,
  275833003: False,
  269828009: False,
  237001001: False,
  177765008: False,
  234336002: False,
  232965003: False,
  445528004: False,
  288086009: False}}

In [15]:
for flag in RESULTS:
    
    col = pd.Series(RESULTS[flag])
    col = col.to_frame(name = flag)
    data[flag] = col

data

,description,is_procedure,is_therapy
code,,,
23426006,Measurement of respiratory function (procedure),True,False
3802001,Dental application of desensitizing medicament...,False,False
223470000,Discussion about signs and symptoms (procedure),False,False
58000006,Patient discharge (procedure),True,False
287664005,Ligation of bilateral fallopian tubes (procedure),False,False
...,...,...,...
434363004,Human epidermal growth factor receptor 2 gene ...,NaN,NaN
433114000,Human epidermal growth factor receptor 2 gene ...,NaN,NaN
105376000,Transesophageal echocardiography (procedure),NaN,NaN
408919008,Psychosocial care (regime/therapy),NaN,NaN
171126009,Tuberculosis screening (procedure),NaN,NaN

In [19]:
data.iloc[203:215]

,description,is_procedure,is_therapy
code,,,
456191000124101,Postoperative care for dental procedure (regim...,NaN,NaN
47758006,Hepatitis B surface antigen measurement (proce...,NaN,NaN
252160004,Standard pregnancy test (procedure),NaN,NaN
699253003,Surgical manipulation of joint of knee (proced...,NaN,NaN
225338004,Risk assessment (procedure),NaN,NaN
410006001,Digital examination of rectum (procedure),NaN,NaN
305342007,Admission to ward (procedure),NaN,NaN
418023006,Computed tomography of chest abdomen and pelv...,NaN,NaN
370995009,Health risks education (procedure),NaN,NaN
398171003,Hearing examination (procedure),NaN,NaN
1155885007,Repair of aortic valve (procedure),NaN,NaN
173291009,Simple extraction of tooth (procedure),NaN,NaN